spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  application:
    name: stock-service
  datasource:
    url: jdbc:postgresql://localhost:5433/stock_db
    username: postgres
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update

kafka:
  topic:
    name: stock-updated
  delete-topic:
    name: delete-process-byId-from-outbox
  brokers: localhost:59092